### Python Codes

In [1]:
# Create 2nd array from existing array

import array as arr

vals=arr.array('i',[2,4,6,8,10])
print(vals)

newvals=arr.array(vals.typecode, [a*a for a in vals])
newvals.reverse()
print('Reversed')

i=0
while i<len(newvals):
    print(newvals[i],end=' ')
    i+=1


array('i', [2, 4, 6, 8, 10])
Reversed
100 64 36 16 4 

In [2]:
# Create array from user input

from array import *

a=int(input('enter the length of array :')) #  --- >4
values=array('i',[])

for i in range(a):
    val=int(input('enter the number: ')) # ------ >11,22,33,44
    values.append(val)
print(values)   # ----- >array('i',[11,22,33,44]
b=int(input('enter number for search :')) #------ >33
for i in range(a):
    if values[i]==b:
        print(i)
        break
print(values.index(b))


enter the length of array :6
enter the number: 1
enter the number: 2
enter the number: 3
enter the number: 4
enter the number: 5
enter the number: 6
array('i', [1, 2, 3, 4, 5, 6])
enter number for search :5
4
4


In [3]:
# Create 3 dimensional array using single big array

from numpy import *
arr=array([
            [1,2,3,7,8,9],
            [4,5,6,10,11,12]
         ])
arr1=arr.flatten()
arr2=arr1.reshape(2,2,3)
print(arr2)
print('type=',arr2.dtype)
print('dimension=',arr2.ndim)
print('shape=',arr2.shape)
print('size=',arr2.size)


[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
type= int32
dimension= 3
shape= (2, 2, 3)
size= 12


In [4]:
# Matirx multiplication

from numpy import *

m1=matrix('1,4,2;3,8,4;5,9,6;7,8,8')
m2=matrix('5,9,6,6;7,7,8,8;1,6,4,2')
m=m1*m2
print(m)
print()
print(diagonal(m))
print('type=',m.dtype)
print('dimension=',m.ndim)
print('shape=',m.shape)
print('size=',m.size)


[[ 35  49  46  42]
 [ 75 107  98  90]
 [ 94 144 126 114]
 [ 99 167 138 122]]

[ 35 107 126 122]
type= int32
dimension= 2
shape= (4, 4)
size= 16


In [5]:
# Count number of evens and odds in a list:

def segre(lst):
    evn=0
    odd=0
    for i in lst:
        if i%2==0:
            evn+=1
        else:
            odd+=1
    return evn,odd

lst=[22,33,44,55,66,77,88,9,78,67,70]
seg1,seg2=segre(lst) 
print("Number of evens:",seg1)
print("number of odds: ",seg2)


Number of evens: 6
number of odds:  5


In [6]:
# Fibonacci sequence

def fib(n):
    a = 0
    b = 1
    if n<0:
        print('enter positive integers')
    elif n==1:
        print(a,end=' ')
    else:
        print(a,end=' ')
        print(b,end=' ')
        for i in range(2,n):
            c=a+b
            a=b
            b=c
            print(c,end=' ')
fib(10)


0 1 1 2 3 5 8 13 21 34 

In [7]:
# Find factorial

def fact(n):
    f=1
    for i in range(1,n+1):
        f=f*i
    return f

x=6
res=fact(x)
print('factorial of',x,'is',res)


factorial of 6 is 720


In [8]:
# Recursion, Set limit manually

import sys
sys.setrecursionlimit(1000)
print(sys.getrecursionlimit())
i=0
def rec():
    global i
    i+=1
    print("hello",i)
    rec()
rec()



1000
hello 1
hello 2
hello 3
hello 4
hello 5
hello 6
hello 7
hello 8
hello 9
hello 10
hello 11
hello 12
hello 13
hello 14
hello 15
hello 16
hello 17
hello 18
hello 19
hello 20
hello 21
hello 22
hello 23
hello 24
hello 25
hello 26
hello 27
hello 28
hello 29
hello 30
hello 31
hello 32
hello 33
hello 34
hello 35
hello 36
hello 37
hello 38
hello 39
hello 40
hello 41
hello 42
hello 43
hello 44
hello 45
hello 46
hello 47
hello 48
hello 49
hello 50
hello 51
hello 52
hello 53
hello 54
hello 55
hello 56
hello 57
hello 58
hello 59
hello 60
hello 61
hello 62
hello 63
hello 64
hello 65
hello 66
hello 67
hello 68
hello 69
hello 70
hello 71
hello 72
hello 73
hello 74
hello 75
hello 76
hello 77
hello 78
hello 79
hello 80
hello 81
hello 82
hello 83
hello 84
hello 85
hello 86
hello 87
hello 88
hello 89
hello 90
hello 91
hello 92
hello 93
hello 94
hello 95
hello 96
hello 97
hello 98
hello 99
hello 100
hello 101
hello 102
hello 103
hello 104
hello 105
hello 106
hello 107
hello 108
hello 109
hello 110
hel

RecursionError: maximum recursion depth exceeded while calling a Python object

In [9]:
# Factorial by recursion

def fact(n):
    if n==0:
        return 1
    else:
        return n*fact(n-1)

a=5
res=fact(a)
print(res)


120


In [10]:
# Lambda funtion

sqr=lambda m,n: m+n

a,b=9,10
res=sqr(a,b)
print(res)


19


In [11]:
# Filter Map Reduce

from functools import reduce

lst=[1,2,3,4,5,6,7,8,9,10]
flt=list(filter(lambda n:n%2==0,lst))
mp=tuple(map(lambda n:n*2,flt))
rd=reduce(lambda a,b:a+b,mp)
print(flt)
print(mp)
print(rd)


[2, 4, 6, 8, 10]
(4, 8, 12, 16, 20)
60


In [12]:
# Decorators

def div(a,b):
	print(a/b)

def add_fun(func):
	def inner(a,b):
		if a<b:
			a,b=b,a
		return func(a,b)


	return inner

div1=add_fun(div)
div1(20,5)


4.0


In [13]:
# Compare 2 objects

class computer:
    def __init__(self):
        self.name='shree'
        self.age=28
    def compare(self,other):
        if self.age==other.age:
            print('they are same')
        else:
            print('not same')
com1=computer()
com2=computer()

com1.compare(com2)


they are same


In [14]:
# Types of variables……Class and Instance
# Instance variable

class computer:
    def __init__(self):
        self.name='shree'
        self.age=28
    def compare(self,other):
        if self.age==other.age:
            print('they are same')
        else:
            print('not same')
com1=computer()
com2=computer()

com1.compare(com2)


they are same


In [15]:
# Types of variables(Instance/Class)
# class variable /static variable

class car:
    wheels=6
    def __init__(self):
        self.milage=20
        self.brand='Volkswagen'
veh1=car()
veh2=car()
veh2.milage=30
car.wheels=8
print(veh1.milage,veh1.brand,veh1.wheels)
print(veh2.milage,veh2.brand,veh2.wheels)


20 Volkswagen 8
30 Volkswagen 8


In [16]:
# Take inputs from user First,Last Name and male or female and accordingly add prefix Mr or Ms

Fn=input('Enter First name : ')
Ln=input('Enter Last name : ')
Gn=input('Enter Male or Female : ')
G=Gn.upper() #---- Converts taken input to all upper cases
if G=='MALE':
    print('Mr',Fn,Ln)
else:
    print('Ms',Fn,Ln)


Enter First name : Shreenidhi
Enter Last name : S
Enter Male or Female : male
Mr Shreenidhi S


In [17]:
# Types of Methods----Instance,Class,Static

class Tenth:
    school='Telusko'
    def __init__(self,m1,m2,m3):
        self.m1=m1
        self.m2=m2
        self.m3=m3
    def avrg(self): #-------Instance method
        return (self.m1+self.m2+self.m3)/3
    def get_mar(self):
        print(self.m1)
    def chng_mar(self,chn):
        self.m1=chn
        print(self.m1)
    @classmethod
    def get_info(cls): #--------Class method
        print(cls.school)
    @staticmethod
    def infoo(): #---------Static method
        print('Send Off')

stu1=Tenth(98,77,87)
stu2=Tenth(78,100,92)
print(stu1.avrg())#Instance
print(stu2.avrg())#Instance
stu1.get_mar()  # accessor
stu2.chng_mar(35) # mutator
Tenth.get_info() #class method
Tenth.infoo() #static method



87.33333333333333
90.0
98
35
Telusko
Send Off


In [18]:
# Inner Class
# Inner class with object created outside outer class

class student:
    def __init__(self,name,rollno):
        self.name = name
        self.roll = rollno

    def show(self):
        print(self.name,self.roll)
    class laptop:
        def __init__(self,proc,ram,comp):
            self.proc=proc
            self.ram=ram
            self.comp=comp
        def show(self):
            print(self.proc,self.ram,self.comp)
s1 = student('Dave',45)
s2 = student('tina',54)
print('S1 values are: ',s1.name,s1.roll)
s1.show()

lap1=student.laptop('i5','8gb','Acer')
print(lap1.proc,lap1.ram,lap1.comp)
lap1.show()



S1 values are:  Dave 45
Dave 45
i5 8gb Acer
i5 8gb Acer


In [19]:
# Inner Class
# Inner class with object created inside outer class

class student:
    def __init__(self,name,rollno):
        self.name = name
        self.roll = rollno
        self.lap=self.laptop('i5','8gb','Acer') # ------ Object of inner class

    def show(self):
        print(self.name,self.roll)
        self.lap.show() #-----call method
    class laptop: # ----------Inner class
        def __init__(self,proc,ram,comp):
            self.proc=proc
            self.ram=ram
            self.comp=comp
        def show(self): #------inner class method
            print(self.proc,self.ram,self.comp)

s1 = student('Dave',45)
s2 = student('tina',54)
print(s1.name,s1.roll)
print(s1.lap.proc,s1.lap.ram,s1.lap.comp) #------print variables of inner class
s1.show() #-----call student class method
s1.lap.show() #----call laptop class method
#----OR
lap1=s1.lap # Inner class 1st object
lap2=s2.lap # Inner class 2nd object
lap1.show() # call inner class method from 1st object
lap2.show() # call Inner class method from 2nd object

Dave 45
i5 8gb Acer
Dave 45
i5 8gb Acer
i5 8gb Acer
i5 8gb Acer
i5 8gb Acer


In [20]:
# Inheritance (single level, multi level,multiple)

class A:
    def feature1(self):
        print('feature 1')
    def feature2(self):
        print('feature 2')
class B:
    def feature3(self):
        print('feature 3')
    def feature4(self):
        print('feature 4')
class C(B):              #-----------Single level inheritance
    def feature5(self):
        print('feature 5')
    def feature6(self):
        print('feature 6')
class D(C):             #------------Multi level inheritance, inherits C(B) to D
    def feature7(self):
        print('feature 7')
    def feature8(self):
        print('feature 8')
class E(A,B):          #-------------Multiple inheritance, inherits A,B
    def feature9(self):
        print('feature 9')
    def feature10(self):
        print('feature 10')
a1=A()
b1=B()
c1=C()
d1=D()
e1=E()
a1.feature1() #---------- A has feature 1,2
a1.feature2()
b1.feature3() #---------- B has feature 3,4
b1.feature4()
c1.feature3() #---------- C has feature 3,4,5,6
c1.feature4()
c1.feature5()
c1.feature6()
d1.feature3() #---------- D has feature 3,4,5,6,7,8
d1.feature4()
d1.feature5()
d1.feature6()
d1.feature7()
d1.feature8()
e1.feature1() #---------- E has feature 1,2,3,4,9,10
e1.feature2()
e1.feature3()
e1.feature4()
e1.feature9()
e1.feature10()

feature 1
feature 2
feature 3
feature 4
feature 3
feature 4
feature 5
feature 6
feature 3
feature 4
feature 5
feature 6
feature 7
feature 8
feature 1
feature 2
feature 3
feature 4
feature 9
feature 10


In [21]:
# Constructor in inheritance
# Single level inheritance

class A:
    def __init__(self):
        print('A init')
    def feature1(self):
        print('feature 1')
    def feature2(self):
        print('feature 2')

class B(A):
    def __init__(self):
        super().__init__() # calls init frm super class & without super() if init in b not available it calls init of A
        print('B init')
    def feature1(self):
        print('feature 3')
    def feature4(self):
        print('feature 4')
c=B()


A init
B init


In [22]:
# MRO---Method resolution order

class A:
    def __init__(self):
        print('A init')
    def fea1(self):
        print('feat1')
class B:
    def __init__(self):
        print('B init')
    def fea1(self):
        print('fea2')
    def fea6(self):
        print('fea6')
class C(A,B):
    def __init__(self):
        super().__init__() #-----calls init from parent/super class uses MRO--method resolution order so here its class A
        print('C init')
    def feat(self):
        super().fea6()
    
c1=C()
c1.fea1() #----- both class A & B contains fea1 method still it call from class A bcoz of MRO
c1.feat() #----- using super().method() we can also call other methods

A init
C init
feat1
fea6


In [23]:
# Duck Typing

class module1: #-------class of a ide
    def software(self):
        print('run succesfull from mod1')
class module2: #-------class of a ide
    def software(self):
        print('run succesfull from mod2')

class backend: #-------class of a ide
    def software(self):
        print('Run Successful')

class laptop: #----class of a device
    def application(self,run):
        run.software()
class desktop: #---class of a device
    def application(self,run):
        run.software()

ide=module2() #------we can change the class of object but it should have software method
device1=laptop()
device1.application(ide) #-----we can pass obj of any class to device object provided it should have software() method



run succesfull from mod2


In [24]:
# Operator overloading

class student:
    def __init__(self,m1,m2,m3):
        self.m1=m1
        self.m2=m2
        self.m3=m3
    def __add__(self, other): #-------- __add__ operator overload
        English = self.m1+other.m1
        Kannada = self.m2+other.m2
        Hindi =   self.m3+other.m3
        return English,Kannada,Hindi
    def __gt__(self, other): #-------- __gt__ greater than overload
        a=self.m1+self.m2+self.m3
        b=other.m1+other.m2+other.m3
        print(a, b)
        if a>b:
            return True
        else:
            return False
    def __str__(self): #------ return s1/s2
        return '{} {} {}'.format(self.m1,self.m2,self.m3)


s1=student(100,60,70)
s2=student(55,78,90)
s3=s1+s2
print("English:Kannada:Hindi=",s3)

if s1>s2:
    print("s1 wins")
else:
    print('s2 wins')
    
print('Print s1 :',s1)
print('Print s2 :',s2)


English:Kannada:Hindi= (155, 138, 160)
230 223
s1 wins
Print s1 : 100 60 70
Print s2 : 55 78 90


In [25]:
# Abstract Class and Abstract Method

from abc import ABC,abstractmethod
class computer(ABC): #--------Abstract class
    @abstractmethod
    def process(self): #---- Abstract method
        pass
class laptop(computer): # ------ Inheriting abstract class mandatory to have method process
    def process(self):
        print('In laptop')
    def proc(self):
        print('process')
class programmer():# if we pass argument of laptop it works but not of blackboard bcoz its not compulsion for blackboard to have process it doesn't inherit abstract class
    def code(self,pro):
        print('Type code')
        pro.process()
class blackboard():
    def write(self):
        print('writing in chalk')
#com=computer() #-----we cannot create a class / object of abstact class
#com.process()
com1=laptop()
com1.process()
com1.proc()

com2=programmer()
com2.code(com1)

com3=blackboard()
com3.write()

In laptop
process
Type code
In laptop
writing in chalk


In [26]:
# Method OverLoading AND Method OverRiding

# Method Overloading

class addition:
    def __init__(self):
        pass

    def adtn(self,a=None,b=None,c=None):

        s = 0
        if a!=None and b!=None and c!=None:
            s=a+b+c
        elif a!=None and b!=None:
            s=a+b
        elif a!=None:
            s=a
        return s
ad=addition()
x=ad.adtn(2,4)
print(x)


6


In [27]:
# Method Over riding

class A:
    def rep(self):
        print('Hello Good Morning')
class B(A):
    def rep(self):
        print('Hello Good Afternoon')
b=B()
b.rep()

Hello Good Afternoon


In [28]:
# Create object of patient and doctor, 
# pass arguments(code,name,age,doctorname,billamount) in to patient class and 
# pass arguments(doctor and patient list)
# create two method in doctor class one should return max of age, other should return sorted bill amount 
# and call methods from main program
# create few patient objects and make a list of it and pass to doctor class

class patient:
    def __init__(self,code,name,age,doctorname,billamount):
        self.code=code
        self.name=name
        self.age=age
        self.doctorname=doctorname
        self.bamt=billamount

class Doctor(patient):
    def __init__(self,doctor1,patientlist):
        self.doctor1=doctor1
        self.patientlist=patientlist
    def findpatientwithmaxage(self):
        l=[pat1.age,pat2.age,pat3.age,pat4.age]
        ll=max(l)
        print('Max age=',ll)
        if pat1.age==ll:
            print(pat1.code,pat1.name,pat1.age,pat1.doctorname)
        elif pat2.age==ll:
            print(pat2.code,pat2.name,pat2.age,pat2.doctorname)
        elif pat3.age==ll:
            print(pat3.code,pat3.name,pat3.age,pat3.doctorname)
        elif pat4.age==ll:
            print(pat4.code,pat4.name,pat4.age,pat4.doctorname)
    def sortpatientbybillamount(self):
        s=[pat1.bamt,pat2.bamt,pat3.bamt,pat4.bamt]
        s.sort()
        for i in range(len(s)):
                print('Bill amount:=',s[i])



pat1=patient(100,'John',26,'David',1000)
pat2=patient(101,'Jacob',38,'Garry',2000)
pat3=patient(102,'Ramesh',56,'Abdul',4000)
pat4=patient(103,'Ria',57,'Prajwal',4500)
patientlist=[pat1,pat2,pat3,pat4]
doctor1='None'
doc=Doctor(doctor1,patientlist)

if __name__=="__main__":
    doc.findpatientwithmaxage()
    doc.sortpatientbybillamount()



Max age= 57
103 Ria 57 Prajwal
Bill amount:= 1000
Bill amount:= 2000
Bill amount:= 4000
Bill amount:= 4500


In [29]:
# Iterators
# Create a class and object for iteration and using that object call iter and next

class topseven:
    def __init__(self): #------- Initialize starting value
        self.itrstrt=1
    def __iter__(self): #------- Returns Iterator Object
        return self
    def __next__(self): #------- calling next is used to iterate from one value to other
        if self.itrstrt<=10:
            val=self.itrstrt
            self.itrstrt+=1
            return val
        else:
            raise StopIteration #------ For loop has to be stopper with StopIteration

TS=topseven()
print(TS.__next__()) #----- just calls next method
for i in TS: #-----starts from 2 to 10
   print(i)

1
2
3
4
5
6
7
8
9
10


In [30]:
# Generators

def topten():
    i=1
    while i<=10: #------ While loop bcuz for loop will again call iterator so 
        val=i*i
        yield val #----- this yield word makes the function generator 
        i+=1
        
        
vals=topten() #----- return generator object
for i in vals: #---- inturn call iter and next which will be supported by yield
    print(i)


1
4
9
16
25
36
49
64
81
100


In [31]:
# Exception Handling

a=10
b=0

try:
    print('resource open') #-------Data base open
    print(a/b) #------ critical statement
except ZeroDivisionError as e: #----- handles error
    print('ERROR : Number cannot be divided by 0 or',e)

try:
    k=int(input('Enter a number: '))
    print(k)
except ValueError as e:
    print('Invalid input, please enter number')

except Exception as e:
    print("Something wrong",e)

finally: #------ finally executes if error or no error
    print('resource closed')
    print('Bye')

resource open
ERROR : Number cannot be divided by 0 or division by zero
Enter a number: 4
4
resource closed
Bye


In [32]:
# Multithreading
# This program will be handles by 3 threads main thread, thread 1 for hello , thread 2 for hi

from time import sleep
from threading import *
class Hello(Thread):
    def run(self):
        for i in range(5):
            print('Hello')
            sleep(1) #------ Thread 1 put to sleep for 1 sec after printing hello

class Hi(Thread):
    def run(self):
        for i in range(5):
            print('Hi')
            sleep(1) #------ Thread 2 put to sleep for 1 sec after printing hi

t1=Hello()
t2=Hi()

t1.start() #------- Activates separate thread
sleep(0.3)
t2.start()
t1.join() #------- without join main thread will execute 'Process Complete' in middle of execution of 2 threads
t2.join()
print('Process Complete')


Hello
Hi
Hello
Hi
Hello
Hi
Hello
Hi
Hello
Hi
Process Complete


In [33]:
# Algorithms

# Linear search using 'while' loop

pos=-1
def search(lst,n):

    i=0
    while i<len(lst):
        if lst[i]==n:
            globals()['pos']=i

            return True
        i+=1
    return False

lst=[5,8,4,6,9,2]
n=9
if search(lst,n):
    print('Found at',pos+1)
else:
    print('Not Found',pos)


Found at 5


In [34]:
# Linear Search using 'for' loop

pos=-1
def search(lst,n):
    q=0
    for i in lst:
        if i==n:
            globals()['pos']=q

            return True
        q+=1
    return False

lst=[5,8,4,6,9,2]
n=4
if search(lst,n):
    print('Found at',pos+1)
else:
    print('Not Found',pos)


Found at 3


In [35]:
# Binary Search

pos=-1
def search(lt,n):
    lt.sort()
    print(lt)
    
    l=0
    u=len(lt)-1
    while l<=u:
        mid=(l+u)//2
        if lt[mid]==n:
            globals()['pos']=mid
            return True
        else:
            if lt[mid]<n:
                l=mid+1
            else:
                u=mid-1
    return False

lt=[33,2,3,44,67,98,1,17,45,33,23,99,100,7,65]
n=67
if search(lt,n):
    print('Found at =',pos+1)
else:
    print('Not Found')

[1, 2, 3, 7, 17, 23, 33, 33, 44, 45, 65, 67, 98, 99, 100]
Found at = 12


In [36]:
# Bubble sort technique
# For 6 numbers 5 iterations is required 

def sort(lst):
    for i in range(len(lst)-1,0,-1): # Outer loop navigates from 5,4,3,2,1
        for j in range(i): # Inner loop wrt outer loop follows 5,4,3,2,1 number of swappings
            if lst[j]>lst[j+1]:
                temp=lst[j]
                lst[j]=lst[j+1]
                lst[j+1]=temp


lst=[7,5,4,3,2,1]
print('Actual sequence :',lst)
sort(lst)
print('sorted sequence :',lst)

Actual sequence : [7, 5, 4, 3, 2, 1]
sorted sequence : [1, 2, 3, 4, 5, 7]


In [37]:
# Selection sort technique

# Saves processor energy and time

def sort(lst):
    for i in range(len(lst)-1):       # ------ since 6 elements requires 5 iterations
        min=i                         #------ every iteration 1st element is considered minimum
        for j in range(i,len(lst)):  #------ inner loop works on checking smallest number
            if lst[min]>lst[j]:      #------ if min value is greater than any other no in sequence, assign new index to min
                min=j

        temp=lst[min]               #------ swap after checking complete sequence
        lst[min]=lst[i]
        lst[i]=temp

lst=[3,7,10,6,5,9,89,1]
print('Actual sequence :',lst)
sort(lst)
print('sorted sequence :',lst)

Actual sequence : [3, 7, 10, 6, 5, 9, 89, 1]
sorted sequence : [1, 3, 5, 6, 7, 9, 10, 89]
